### ISSUE TITLE
api authorization issue

### ISSUE THREAD

**Issue by meetvora2006** [kilokeith/soundcloud-soundmanager-player#16]
Hii,

i am getting this error while i am running the code 

"NetworkError: 404 Not Found - http://api.soundcloud.com/resolve?url=http://soundcloud.com/royalbassrecords/sets/dubstep/&format=json&consumer_key=524c5acd5e5c401654259eb487c4bfb2&callback=jQuery18204917505575175545_1430373181944&_=1430373182211"

i also change the code

"var scplayer = new SoundCloudPlayer([
				//"/diplo/wobble-prod-diplo",
				"/dev-meet/jogi-thai-ne-chalya-prashant-shah/"
			],{
			  consumer_key: "392e116ca1dc8fce8978a264cf51f557",
			   autoplay: false ,
		       loop: false ,
			   toggle_pause: true ,
			   preload: true
		});"

what to do now?

**Comment by kilokeith** [comment]
Did you try looking up that set? http://soundcloud.com/royalbassrecords/sets/dubstep/  It doesn't exist any more which is why you're getting a 404. This is a pretty old repo, not really maintained any more. So the reference tracks shouldn't be counted on.

**Comment by meetvora2006** [comment]
Thanks a lot sir..it's working now..i have some other doubt..i am writing it in other issue
