### ISSUE TITLE
Add to Queue /playlist + browser compatibility 

### ISSUE THREAD

**Issue by meetvora2006** [kilokeith/soundcloud-soundmanager-player#17]
Hi Keith,

I'm trying to implement an "Add to Queue / Playlist" button so that amongst a dozen tracks I could add maybe 5 to the "Now Playing" Queue. Any tips on how I can accomplish that?

Also any idea on the browser compatibility?

**Comment by fxcutz** [comment]
You could try to just push some items to the main array which contains the songs it's already playing.

**Comment by kilokeith** [comment]
There's an scplayer. add_tracks() method. Pass a url or an array of urls to it.
