### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by torstah** [kilokeith/soundcloud-soundmanager-player#5]
Hi 

Do you know how to get this working for iPhone / iOS ?

Thanks!

/T

**Comment by scottwvw** [comment]
Hi,

I'm having an issue with the playlist out of the box, no matter what I do I can't seem to get this working on ios safari. I've got it hosted here: http://scottvanwinden.com/freelance/soundcloud-test/examples/playlist.html

Any advice would be greatly appreciated!

Thanks in advance

S
