### ISSUE TITLE
Is it possible to delete entire playlist, add new playlist?

### ISSUE THREAD

**Issue by denitto** [kilokeith/soundcloud-soundmanager-player#8]
Hey Keith,

Just wondering if there is an easy way to delete tracks (all tracks would be great, too).  We're working on a feature whereby users can select genre-specific playlists at a click, and the destroy() function seems to make the player inoperable (I lose the ability to add tracks dynamically).  

Still loving your script.  Cannot wait to show you the project my team is using it for.  Since I'm guessing you're a dubstep fan, for now I'll just tell you it's Skrillex/Owsla related.  ;)  I also hope we impress you with the styling and integration.

**Comment by 0910** [comment]
@denitto  Awesome work on Nest! Could you share the code you are using to Add new tracks and groups?

Thanks!

**Comment by denitto** [comment]
Hey Emanuel:

Really stoked you are interested.  I’m happy to share the code!  Will do so asap today or tomorrow.

— 

Nicholas DeNitto / Technical Director
213-613-1246 / manufactur.co

DISCLAIMER : This message contains information which may be confidential and/or privileged and is intended only for the use of the addressee(s). Any use, disclosure or copying of this message or any part thereof by any person other than such addressee(s) is unauthorized and strictly prohibited. If you have received this message in error, please notify the sender by return e-mail and delete the message. Thank you for your cooperation.

On March 1, 2016 at 5:25:11 AM, Emanuel Dobao (notifications@github.com) wrote:

@denitto Awesome work on Nest! Could you share the code you are using to Add new tracks and groups?

Thanks!

**Comment by 0910** [comment]
oh cool @denitto , I'll be very grateful :)

**Comment by denitto** [comment]
Hey @0910:

So, not sure what you needed, but here are two functions I wrote to add tracks - #1 (and lists of tracks - #3):  

[custom-sc.js](http://nesthq.com/wp-content/themes/nest/js/custom-sc.js)

Is this what you wanted to see?

**Comment by 0910** [comment]
@denitto That's exactly what i was looking for. Thanks man!
